name: Build Android APK with Versioning and Release

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating releases
    steps:
      # 1. Check out the public repo's code
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for versioning

      # 2. Generate version number based on commit count
      - name: Generate Version Number
        id: version
        run: |
          # Get the number of commits on main branch
          COMMIT_COUNT=$(git rev-list --count HEAD)
          # Create version number (e.g., 1.0.1, 1.0.2, etc.)
          VERSION="1.0.$COMMIT_COUNT"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Generated version: $VERSION"

      # 3. Update package.json version (which Capacitor uses)
      - name: Update Package.json Version
        run: |
          # Update version in package.json
          npm version ${{ steps.version.outputs.VERSION }} --no-git-tag-version

      # 4. Update Android version in build.gradle
      - name: Update Android Version
        run: |
          # Update version name and code in build.gradle
          COMMIT_COUNT=$(git rev-list --count HEAD)
          sed -i "s/versionName \"[^\"]*\"/versionName \"${{ steps.version.outputs.VERSION }}\"/" android/app/build.gradle
          sed -i "s/versionCode [0-9]*/versionCode $COMMIT_COUNT/" android/app/build.gradle

      # 5. Set up Java (JDK) for Android builds
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 6. Set up Node.js for Capacitor CLI
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      # 7. Install Capacitor dependencies from package.json
      - name: Install Dependencies
        run: npm ci

      # 8. Sync the web assets into the native Android project
      - name: Capacitor Sync
        run: npx cap sync android

      # 9. Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      # 10. Build the Release APK (signed with debug key for now)
      - name: Build Release APK
        run: |
          cd android
          ./gradlew assembleRelease

      # 11. Rename APK with custom name and version number
      - name: Rename APK
        run: |
          mkdir -p release
          cp android/app/build/outputs/apk/release/app-release.apk release/syedarhamraza.portfolio-v${{ steps.version.outputs.VERSION }}.apk

      # 12. Create GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          release_name: Release v${{ steps.version.outputs.VERSION }}
          body: |
            ## What's Changed
            - Auto-generated release for version ${{ steps.version.outputs.VERSION }}
            - Build from commit: ${{ github.sha }}
            
            ## Download
            Download the APK file below to install on your Android device.
          draft: false
          prerelease: false

      # 13. Upload APK to Release
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/syedarhamraza.portfolio-v${{ steps.version.outputs.VERSION }}.apk
          asset_name: syedarhamraza.portfolio-v${{ steps.version.outputs.VERSION }}.apk
          asset_content_type: application/vnd.android.package-archive

      # 14. Also upload as build artifact (for workflow downloads)
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: syedarhamraza.portfolio-v${{ steps.version.outputs.VERSION }}
          path: release/syedarhamraza.portfolio-v${{ steps.version.outputs.VERSION }}.apk
